import json
import re
from core.llm.ai_framework_adaptor import AIFrameworkAdaptor
from agents.Pramana.prompts import PRAMANA_MASTER_PROMPT
from core.rag.retriever import Retriever

class PramanaAgent:
    def __init__(self, db_path, collection_name, prompt_type="qa", config=None):
        self.mode = "qa"
        self.config = config or {}
        try:
            self.retriever = Retriever(db_path, collection_name)
        except:
            self.retriever = None
        
        self.llm = AIFrameworkAdaptor()
        self.state = "IDLE"

    def execute(self, user_input, session_data):
        """
        user_input: "Generate tests for this feature"
        session_data: Must contain 'final_solution' (from Solvo) or code snippet.
        """
        self.state = "TESTING"
        
        # 1. Get Context
        # Try to get the Code generated by Sutra, or the Plan from Solvo
        prev_response = session_data.get("last_agent_response", "")
        plan = session_data.get("uploaded_doc_content", "")
        
        # 2. Construct Prompt
        prompt = f"""{PRAMANA_MASTER_PROMPT}

# THE REQUIREMENT (PLAN)
{plan}

# THE CODE TO TEST (FROM PREVIOUS STEP)
{prev_response}

# USER INSTRUCTION
{user_input}
"""
        print("\n⚖️ Pramana is generating proofs...")
        response = self.llm.generate_content(prompt)

        # 3. Parse Output (Reuse robust parser logic)
        try:
            json_match = re.search(r'\{.*\}', response.text, re.DOTALL)
            if json_match:
                result_json = json.loads(json_match.group(0))
                
                output_text = "### ⚖️ Test Generation Complete\n\n"
                output_text += f"**Summary:** {result_json.get('test_plan_summary', 'Tests generated.')}\n\n"
                
                for file in result_json.get("test_files", []):
                    output_text += f"**File:** `{file['path']}`\n"
                    output_text += f"```java\n{file['code_content']}\n```\n\n"
                
                session_data["last_agent_response"] = output_text
            else:
                session_data["last_agent_response"] = response.text
                
        except Exception as e:
            session_data["last_agent_response"] = f"🚨 Pramana Error: {e}\nRaw: {response.text}"
            
        self.state = "DONE"